repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args:
          - --fix
          - --select
          - ALL
          - --ignore
          - E501,D401,D417  # Combine ignored checks in a comma-separated list
      - id: ruff-format  # Run the formatter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-setuptools]  # Add any necessary stub packages
