name: CI Workflow
on:
  push:
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install global dependencies with Poetry
        run: |
          poetry install

      - name: Lock dependencies for training-pipeline
        run: |
          cd training-pipeline
          poetry lock

      - name: Setup and check training-pipeline
        run: |
          cd training-pipeline
          poetry install
          poetry run mypy .

      - name: Lock dependencies for feature-pipeline
        run: |
          cd feature-pipeline
          poetry lock

      - name: Setup and check feature-pipeline
        run: |
          cd feature-pipeline
          poetry install
          poetry run mypy .